# ASP.NET Core	
# Build and test ASP.NET Core projects targeting .NET Core.	
# Add steps that run tests, create a NuGet package, deploy, and more:	
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core	

trigger:
- master

pool:
 vmImage: 'ubuntu-latest'

 variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: Installing .NET Core SDK
  inputs:
    version: '2.2.401'
- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build Release
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: Running Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'