# ASP.NET Core	
# Build and test ASP.NET Core projects targeting .NET Core.	
# Add steps that run tests, create a NuGet package, deploy, and more:	
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core	

trigger:
- master

pool:
 vmImage: 'ubuntu-latest'

 variables:
  buildConfiguration: 'Release'
  imageName: anchev/web.api:$(build.buildNumber)

steps:
- task: DotNetCoreInstaller@0
  displayName: Installing .NET Core SDK
  inputs:
    version: '2.2.401'
- task: DotNetCoreCLI@2
  displayName: Restore NuGet Packages
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build Release
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: Running Unit Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: Docker@1
  displayName: Build a Docker Image
  inputs:
    command: Build an image
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DockerHub
    dockerFile: '**/server/**/Dockerfile'
    imageName: ${imageName}
    imageNamesPath:
    restartPolicy: always
- task: Docker@1
  displayName: Push a Docker Image
  inputs:
    command: Push an image
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DockerHub
    dockerFile: '**/server/**/Dockerfile'
    imageName: ${imageName}
    imageNamesPath:
    restartPolicy: always