trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'dev/web.api:$(build.buildNumber)'

steps:
- script: dotnet test ifsc.tcc.Portal.Tests/ifsc.tcc.Portal.Tests.csproj --logger trx
  displayName: Run Unit Tests
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: Docker@1
  displayName: Build an image
  inputs:
    command: Build an image
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DockerHub
    dockerFile: Dockerfile
    imageName: $(imageName)
    imageNamesPath: 
    restartPolicy: always
- task: Docker@1
  displayName: Push an image
  inputs:
    command: Push an image
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: DockerHub
    dockerFile: Dockerfile
    imageName: $(imageName)
    imageNamesPath: 
    restartPolicy: always